baseURL = "https://nirgn975.github.io/devRes/"
languageCode = "en-us"
title = "DevRes"
theme = "devRes"

# themes directory
themesDir = "../.."

[params]
  [params.light]
    background = "#E0E0E0"
    text = "#333333"
    textHover = "#1e70bf"
    border = "#999999"
    headerBackground = "#ffffff"

  [params.dark]
    background = "#303030"
    text = "#B3B3B3"
    textHover = "#bdebfc"
    border = "#666666"
    headerBackground = "#424242"

  [params.analytics]
    [params.analytics.plausible]
      enable = true
      domain = "nir.galon.io"
    [params.analytics.google]
      enable = false
      id = "UA-87725724-1"
