baseURL = "https://example.com/"
languageCode = "en-us"

title = "DevRes"
theme = "devRes"

# themes directory - delete it on our own hugo website.
themesDir = "../.."

[params]
  description = "The best theme for developers resume"
  author = "nirgn975"

  [params.light]
    background = "#E0E0E0"
    text = "#333333"
    textHover = "#1e70bf"
    border = "#999999"
    headerBackground = "#ffffff"

  [params.dark]
    background = "#303030"
    text = "#B3B3B3"
    textHover = "#bdebfc"
    border = "#666666"
    headerBackground = "#424242"

  [params.analytics]
    [params.analytics.plausible]
      enable = true
      domain = "johndoe.com"
    [params.analytics.google]
      enable = false
      id = "UA-xxxxxxxx-1"
